# Exercises week 3.1


## Structure

Each Exercise contains 3 different types of cells, 1 for the description of the exercise and the place where you need to write your code at the locations `#here your code`. Then there is the cell with the hint code, if you need help with the exercise because its not clear what to do or if you need an extra suggestion run the hint cell. At last we have the test cell, if you want to test if your solution is the correct one run this cell and it will tell you if you passed the exercise or not.

### Importing modules

In [14]:
import numpy as np


## Exercise 3.1.1 Matrix Multiplication
Given function `matixmul(arr1, arr2)` return the result of a matrix multiplication

In [17]:
def matrixmul(arr1, arr2):
    return arr1 @ arr2


### Hint Matrix Multiplication
Need a hint run the following cell

In [16]:
from testexercises import hint_matrixmul
hint_matrixmul()

you can use the @ operator to do the matmul


### Test Matrix Multiplication
Want to check if your code is correct? Run the following cell!

In [18]:
from testexercises import test_matrixmul
test_matrixmul(matrixmul)

=========>
All tests passed!!!


## Exercise 3.1.2 Create Matrix
given function `matrix3x3()` return a 3x3 numpy matrix with values ranging from 2 to 10. Like:<br>
[[ 2  3  4]                                                        
 [ 5  6  7]                                                             
 [ 8  9 10]]

In [3]:
def matrix3x3():
    matrix = [
        [], 
        [], 
        [],
    ]

    counter = 2

    for i in range(3):
        for j in range(3):
            matrix[i].append(counter)
            counter += 1
    
    return matrix

[[1, 2, 3], [2, 4, 6], [3, 6, 9]]


### Hint create matrix
Need a hint run the following cell

In [ ]:
from testexercises import hint_matrix3x3
hint_matrix3x3()

### Test create matrix
Want to check if your code is correct? Run the following cell!

In [26]:
from testexercises import test_matrix3x3
test_matrix3x3(matrix3x3)

=========>
All tests passed!!!


## Exercise 3.1.3 append to array
Given function `append_array(arr1, arr2)` append `arr2` to `arr1` and return the result

In [15]:
def append_array(arr1, arr2):
    return np.append(arr1, arr2)

[1 2 3 4 5 6]


### Hint append to array
Need a hint run the following cell

In [ ]:
from testexercises import hint_append_array
hint_append_array()

### Test append to array
Want to check if your code is correct? Run the following cell!

In [16]:
from testexercises import test_append_array
test_append_array(append_array)

=========>
All tests passed!!!


## Exercise 3.1.4 checkerboard pattern (hard)
Given function `checkerboard_pattern(x, y)` where `x` is the width of the board and `y` is the height of the board. the pattern needs to be the following:<br>
if `x = 4` and `y = 4`. the pattern would look like:<br>

[<br>
[0, 1, 0, 1]<br>
[1, 0, 1, 0]<br>
[0, 1, 0, 1]<br>
[1, 0, 1, 0]<br>
] 

and if `x = 8` and `y = 6`:<br>
[<br>
[0, 1, 0, 1, 0, 1, 0, 1]<br>
[1, 0, 1, 0, 1, 0, 1, 0]<br>
[0, 1, 0, 1, 0, 1, 0, 1]<br>
[1, 0, 1, 0, 1, 0, 1, 0]<br>
[0, 1, 0, 1, 0, 1, 0, 1]<br>
[1, 0, 1, 0, 1, 0, 1, 0]<br>
]<br>

make sure you return the matrix as a numpy array

In [48]:
def checkerboard_pattern(x, y):
    board = []

    for row in range(y):
        board.append([])
        for column in range(x):
            board[row].append((row+column) % 2)
    
    return board

board = checkerboard_pattern(7, 7)
for row in board:
    print(row)

[0, 1, 0, 1, 0, 1, 0]
[1, 0, 1, 0, 1, 0, 1]
[0, 1, 0, 1, 0, 1, 0]
[1, 0, 1, 0, 1, 0, 1]
[0, 1, 0, 1, 0, 1, 0]
[1, 0, 1, 0, 1, 0, 1]
[0, 1, 0, 1, 0, 1, 0]


### Hint checkerboard pattern
Need a hint run the following cell

In [ ]:
from testexercises import hint_checkerboard_pattern
hint_checkerboard_pattern()

### Test checkerboard pattern
Want to check if your code is correct? Run the following cell!

In [49]:
from testexercises import test_checkerboard_pattern
test_checkerboard_pattern(checkerboard_pattern)

=========>
All tests passed!!!
